services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword!23
      - MYSQL_DATABASE=codestates
      - MYSQL_USER=pung
      - MYSQL_PASSWORD=pungPassword!23
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
