services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=pung
      - DB_PASSWORD=pungPassword!23
      - DB_DATABASE=codestates
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootPassword!23
      - MYSQL_DATABASE=codestates
      - MYSQL_USER=pung
      - MYSQL_PASSWORD=pungPassword!23
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
